### ISSUE TITLE
[BUG] Overlapping rows when many tables

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/dashboards-query-workbench#190]
**What is the bug?**
<img width="471" alt="Screenshot 2023-10-30 at 12 39 10 PM" src="https://github.com/opensearch-project/dashboards-query-workbench/assets/26328171/2f897ab3-7a82-4720-98e3-e2bd69836014">

Overlapping rows when many tables

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**

 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ps48** [comment]
This coming from an Oui bug: https://github.com/opensearch-project/oui/issues/1118
Overridden for workbench  in this PR: https://github.com/opensearch-project/dashboards-query-workbench/pull/189/commits/1fa6076ea7b7d034716d129f248fb8ce0d536484
