### ISSUE TITLE
[BUG]  Error fetching even with all permissions

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/dashboards-query-workbench#194]
**What is the bug?**
A call is being made to: 
http://localhost:5601/api/spark_sql_console/job/undefined
Which is leading to:
```
{
    "data": {
        "ok": false,
        "resp": "Bad Request",
        "body": "{\n  \"status\": 400,\n  \"error\": {\n    \"type\": \"IllegalArgumentException\",\n    \"reason\": \"Invalid Request\",\n    \"details\": \"Last unit does not have enough valid bits\"\n  }\n}"
    }
}
```

Is there something wrong with setup?

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ps48** [comment]
@derek-ho Can you please verify the bug exists in 2.13? If not can we close this issue?

**Comment by derek-ho** [comment]
Can't reproduce, maybe it was a bug that was fixed, closing
