### ISSUE TITLE
[AUTOCUT] OS Distribution Build Failed for OpenSearch-Dashboards-2.5.0

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/dashboards-query-workbench#21]
@opensearch-ci-bot commented on [Tue Jan 10 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3235)

***Received Error***: **Error building OpenSearch-Dashboards, retry with: ./build.sh manifests/2.5.0/opensearch-dashboards-2.5.0.yml --component OpenSearch-Dashboards**.
                      The distribution build for OpenSearch-Dashboards has failed.
                      Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch-dashboards/5309/consoleFull

---

@kavilla commented on [Tue Jan 10 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3235#issuecomment-1377655332)

```
+ cd plugins/queryWorkbenchDashboards
+ yarn plugin-helpers build --opensearch-dashboards-version=2.5.0
yarn run v1.22.19
error Command "plugin-helpers" not found. Did you mean "plugin_helpers"?
```

**Comment by kavilla** [comment]
@opensearch-project/engineering-effectiveness this one got opened in our repo but it was related to the query workbench component.

**Comment by joshuali925** [comment]
i believe this is fixed by https://github.com/opensearch-project/opensearch-build/pull/3084, closing
