### ISSUE TITLE
[BUG] Async queries should immediately cancelled on button click

### ISSUE THREAD

**Issue by ps48** [opensearch-project/dashboards-query-workbench#221]
**What is the bug?**
We see cases when user clicks on the cancel button, the async query loader is still spinning. 

**How can one reproduce the bug?**
1. Create an async query on workbench
2. Cancel any query in running or failed state. 

**What is the expected behavior?**
The cancel button should immediately stop the queries. 

**What is your host/environment?**
 - OS: 2.11
 - Version 2.11
 - Plugins Workbench

**Comment by noCharger** [comment]
@ps48 are we still tracking 2.12 on this?
