### ISSUE TITLE
[BUG] For Async queries on running click button, the UI takes sometime before going in the running 

### ISSUE THREAD

**Issue by ps48** [opensearch-project/dashboards-query-workbench#224]
**What is the bug?**
For Async queries on running click button, the UI takes sometime before going in the running.

**How can one reproduce the bug?**
1. Select a datasource apart from OpenSearch
2. Enter a spark SQL query
3. Click on run -> There's some delay between the actual run and UI going in running state

**What is the expected behavior?**
There's shouldn't be any delay between hitting run and seeing the UI in running state. 

**What is your host/environment?**
 - OS: 2.11
 - Version 2.11
 - Plugins Workbench

**Comment by noCharger** [comment]
@ps48 are we still tracking 2.12 on this?

**Comment by ps48** [comment]
Moving this to 2.13
