### ISSUE TITLE
[FEATURE] Improvement for query workbench

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/dashboards-query-workbench#303]
**Is your feature request related to a problem?**
There are several improvement needed for query workbench, see below
1. "flint" should not be in the Data Source left dropdown/ flint data sources can be expended-list in there.
2. we dont need to s3_prod_log combo box
3. rename "Data Connections" to tables.

**Do you have any additional context?**

**Comment by anirudha** [comment]
![Screenshot 2024-04-05 at 9 53 59 AM](https://github.com/opensearch-project/dashboards-query-workbench/assets/19362/30e4990f-774e-445e-84aa-4e49914168cb)

**Comment by ps48** [comment]
Closing the issue with MDS feature merged in.
