### ISSUE TITLE
[BUG] Saving a query always overwrites a single saved query

### ISSUE THREAD

**Issue by engechas** [opensearch-project/dashboards-query-workbench#357]
**What is the bug?**
Saving a query from the explorer will always overwrite the existing query, even if they are distinct. This only allows 1 saved query to be present at a time. 

**How can one reproduce the bug?**
1. For a domain that doesn’t have any saved query. Open Observability -> Logs -> Explorer
2. Compose a query
3. Click save
4. Go back to Observability -> Logs -> Explorer to compose a new query
5. Click save using a different name.
6. Verify the original saved query was overwritten instead of a new saved query being created

**What is the expected behavior?**
Saving a new query should not overwrite the existing query. It should be possible to have more than one saved query at a time.

**What is your host/environment?**
 - Version 2.13
 - Plugins SQL

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by xinlamzn** [comment]
this sounds like a bug in log explorer

**Comment by ps48** [comment]
Hi @engechas, 

Thanks you so much for adding the bug report. I see the version you're using is 2.13. We had a fix for this issue that went in 2.14. The tracking issue for in logs component is here: https://github.com/opensearch-project/dashboards-observability/issues/1710. Can you please take a look at the 2.14 version or later?

Closing this ticket, please feel free post your finding in the above mentioned `dashboards-observability issue tracker` 
Thanks!
