### ISSUE TITLE
[BUG] Fix dark mode for query workbench

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/dashboards-query-workbench#74]
**What is the bug?**
A clear and concise description of the bug.
https://future.playground.opensearch.org/app/opensearch-query-workbench
-> dark mode should work consistently with each coloring on each query view.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ps48** [comment]
Fix is pushed to 2.x
